version: '3.1'
services:
    starter:
        image: golang:1.15-stretch
        container_name: starter-go
        restart: always
        volumes:
            - ./:/go
        command: ["/bin/sh", "-c", "while true;do echo hello docker;sleep 1;done"]